---
apiVersion: metal.arges.dev/v1alpha1
kind: Environment
metadata:
  name: default
  namespace: arges-system
spec:
  initrd:
    url: https://github.com/talos-systems/talos/releases/download/v0.4.1/initramfs.xz
  kernel:
    args:
      - initrd=initramfs.xz
      - page_poison=1
      - slab_nomerge
      - slub_debug=P
      - pti=on
      - random.trust_cpu=on
      - ima_template=ima-ng
      - ima_appraise=fix
      - ima_hash=sha512
      - console=tty0
      - console=ttyS0
      - printk.devkmsg=on
      - panic=0
      - talos.platform=metal
      - talos.config=http://10.1.1.12/configdata?uuid=
    url: https://github.com/talos-systems/talos/releases/download/v0.4.1/vmlinuz
