apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: example
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.244.0.0/16
    services:
      cidrBlocks:
        - 10.96.0.0/16
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: MetalCluster
    name: example
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: MetalCluster
metadata:
  name: example
spec:
  controlPlaneEndpoint:
    host: 127.0.0.1
    port: 6443
# ---
# apiVersion: cluster.x-k8s.io/v1alpha3
# kind: Machine
# metadata:
#   labels:
#     cluster.x-k8s.io/cluster-name: example
#     cluster.x-k8s.io/control-plane: 'true'
#   name: example-0
# spec:
#   clusterName: example
#   bootstrap:
#     configRef:
#       apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
#       kind: TalosConfig
#       name: example-0
#   infrastructureRef:
#     apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
#     kind: MetalMachine
#     name: example-0
#   version: 1.18.2
# ---
# apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
# kind: MetalMachine
# metadata:
#   name: example-0
# spec:
#   serverRef:
#     apiVersion: metal.arges.dev/v1alpha1
#     kind: Server
#     name: 00000000-0000-0000-0000-012345678912
#   bmc:
#     endpoint: 127.0.0.1
#     user: admin
#     pass: admin
# ---
# apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
# kind: TalosConfig
# metadata:
#   name: example-0
#   labels:
#     cluster.x-k8s.io/cluster-name: example
# spec:
#   generateType: init
